apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: webapp-MODEL_NAME
      prefix: webapp/MODEL_NAME/
      rewrite: /
      method: POST
      service: MODEL_NAME.KUBEFLOW_NAMESPACE:8889
  name: MODEL_NAME-webapp
  labels:
    app: ghsumm
    role: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8889
    targetPort: "http-server"
  selector:
    app: ghsumm
    role: frontend

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: MODEL_NAME-webapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ghsumm
        role: frontend
    spec:
      containers:
      - name: MODEL_NAME-webapp
        image: gcr.io/aju-dev-demos/ml-pipeline-t2tapp
        imagePullPolicy: Always
        env:
        - name: TFSERVING_HOST
          value: MODEL_NAME.KUBEFLOW_NAMESPACE
        - name: TF_SERVABLE_NAME
          value: MODEL_NAME
        - name: GH_TOKEN
          value: GITHUB_TOKEN
        ports:
        - name: http-server
          containerPort: 8080
